language: python
python: "3.8"

os:
    - linux
dist: xenial

branches:
  only:
    - "master"

cache:
    apt: true
    directories:
        - $HOME/.cache/pip
        - $HOME/wheelhouse
        - $HOME/.local
        - vendor/bundle

env:
    global:
        - BUILD_RUNTIMES=$HOME/.runtimes
        - FORMAT_ALL=true
        - PYTHONDONTWRITEBYTECODE=x

jobs:
  fast_finish: true
  include:
    # Prechecks that we want to run to make sure the deploy is good.
    - stage: precheck
      env: TASK=check-whole-repo-tests
    - env: TASK=lint
    - env: TASK=check-py38
    - stage: deploy
      env: TASK=deploy

script:
    - ./build.sh

stages:
    - precheck
    - name: deploy
      if: type = push

notifications:
  email:
    recipients:
      - david@drmaciver.com
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
      - libgmp-dev
      - shellcheck
