language: c

sudo: false

env: PYTHONDONTWRITEBYTECODE=x

os:
    - linux

branches:
  only:
    - "master"

cache:
    apt: true
    directories:
        - $HOME/.cargo
        - $HOME/.rustup
        - $HOME/.gem
        - $HOME/.cache/pip
        - $HOME/wheelhouse
        - $HOME/.stack
        - $HOME/.local
        - vendor/bundle

env:
    global:
        - BUILD_RUNTIMES=$HOME/.runtimes
        - FORMAT_ALL=true

jobs:
  include:
    # Prechecks that we want to run to make sure the deploy is good.
    - stage: precheck
      env: TASK=check-whole-repo-tests
    - env: TASK=lint
    - env: TASK=check-py36
      sudo: required
      dist: xenial
    - env: TASK=check-rust-tests
    - stage: deploy
      env: TASK=deploy

script:
    - ./build.sh

matrix:
    fast_finish: true

stages:
    - precheck
    - name: deploy
      if: type = push

notifications:
  email:
    recipients:
      - david@drmaciver.com
    on_success: never
    on_failure: change

addons:
  apt:
    packages:
      - libgmp-dev
      - shellcheck
