name: Hypothesis CI

on:
  push:
    branches: [ master , github-actions ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - check-whole-repo-tests
          - lint
          - check-format
          - check-coverage
          - check-conjecture-coverage
          - check-py38
          - check-quality
        python-version: ["3.8"]
        include:
          - task: check-py36
            python-version: "3.6"
          - task: check-py37
            python-version: "3.7"
          - task: check-py39
            python-version: "3.9"
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tests
      run: TASK=${{ matrix.task }} ./build.sh

  test-win:
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - task: check-py38-x64
            python.version: "3.8"
            python.architecture: "x64"
          - task: check-py38-x86
            python.version: "3.8"
            python.architecture: "x86"
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.python-architecture }}
    - name: Install dependencies
      run: |
        pip install --upgrade setuptools pip wheel
        pip install -r requirements/test.txt fakeredis typing-extensions
        pip install hypothesis-python/[all]
    - name: Run tests
      run: python -m pytest --numprocesses auto hypothesis-python/tests/

  test-osx:
    runs-on: macos-latest
    strategy:
      matrix:
        task:
          - check-py38
        python-version: ["3.8"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tests
      run: TASK=${{ matrix.task }} ./build.sh

  specific-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task:
          - check-nose
          - check-pytest43
          - check-django31
          - check-django30
          - check-django22
          - check-pandas111
          - check-pandas100
          - check-pandas25
        python-version: ["3.8"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Run tests
      run: TASK=${{ matrix.task }} ./build.sh

  deploy:
    runs-on: ubuntu-latest
    needs: [test, test-win, test-osx, specific-deps]
    strategy:
      matrix:
        task:
          - deploy
        python-version: ["3.8"]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Deploy package
      run: TASK=${{ matrix.task }} ./build.sh
